### PR TITLE
Show edges of sibling slides

### PR DESCRIPTION
**Pull request by markoffk**
Adding possibility to preview next and previous slides by adding widthOfSiblingSlidePreview parameter.

### CODE REVIEW

**Review by voronianski — DISMISSED** [review]
could you please port this to `src/index.js`?

**Comment by voronianski** [comment]
there are some conflicts in swipe.js

**Comment by Cyberlane** [comment]
@voronianski I would like to have this functionality, and happy to make a new PR with the same changes along with conflicts resolved.
Any objections?

Also, I am uncertain what you meant with your earlier comment of porting the code to `src/index.js`, since you do not have such a file, or did you want the code to be moved there at the same time as this change?

**Comment by voronianski** [comment]
@Cyberlane my comment regarding `index.js` is outdated, nevermind it.

I think it would be better if you will create a new PR and then we can merge it. Thanks!

**Pull request closed without merging**
